//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageInfo", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Models")]
    public partial class MessageInfo : object
    {
        
        private System.DateTime ActionDateTimeField;
        
        private string ContentField;
        
        private int CountField;
        
        private string DescField;
        
        private bool FlashField;
        
        private bool IsReadField;
        
        private ServiceReference1.SMSLang LangField;
        
        private int MessageIdField;
        
        private ServiceReference1.SMSDirectionType MessageTypeField;
        
        private bool MoneyIsRefundedField;
        
        private int NotSentField;
        
        private int PagesField;
        
        private string ReceiverField;
        
        private string SenderField;
        
        private int SentField;
        
        private ServiceReference1.SMSStatus StatusField;
        
        private decimal TariffField;
        
        private string TitleField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this.ActionDateTimeField;
            }
            set
            {
                this.ActionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Flash
        {
            get
            {
                return this.FlashField;
            }
            set
            {
                this.FlashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead
        {
            get
            {
                return this.IsReadField;
            }
            set
            {
                this.IsReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SMSLang Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SMSDirectionType MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MoneyIsRefunded
        {
            get
            {
                return this.MoneyIsRefundedField;
            }
            set
            {
                this.MoneyIsRefundedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotSent
        {
            get
            {
                return this.NotSentField;
            }
            set
            {
                this.NotSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sent
        {
            get
            {
                return this.SentField;
            }
            set
            {
                this.SentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SMSStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tariff
        {
            get
            {
                return this.TariffField;
            }
            set
            {
                this.TariffField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSLang", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Common.Enums")]
    public enum SMSLang : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EN = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSDirectionType", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSDirectionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        In = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Out = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Schedule = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usance = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceOut = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSStatus", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")]
    public enum SMSStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Illegal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotApproved = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCredit = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSent = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitForSend = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proccessing = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorrespondingSendViaHttpPostDetailsModel", Namespace="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Models")]
    public partial class CorrespondingSendViaHttpPostDetailsModel : object
    {
        
        private string MessageField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISendService")]
    public interface ISendService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendSMS", ReplyAction="http://tempuri.org/ISendService/SendSMSResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SendSMSResponse> SendSMSAsync(ServiceReference1.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/OTPSMS", ReplyAction="http://tempuri.org/ISendService/OTPSMSResponse")]
        System.Threading.Tasks.Task<ServiceReference1.OTPSMSResponse> OTPSMSAsync(ServiceReference1.OTPSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SmartOTPSMS", ReplyAction="http://tempuri.org/ISendService/SmartOTPSMSResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SmartOTPSMSResponse> SmartOTPSMSAsync(ServiceReference1.SmartOTPSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetCredit", ReplyAction="http://tempuri.org/ISendService/GetCreditResponse")]
        System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDeilvery", ReplyAction="http://tempuri.org/ISendService/GetDeilveryResponse")]
        System.Threading.Tasks.Task<long> GetDeilveryAsync(string userName, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDelivery", ReplyAction="http://tempuri.org/ISendService/GetDeliveryResponse")]
        System.Threading.Tasks.Task<long> GetDeliveryAsync(string userName, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetMessages", ReplyAction="http://tempuri.org/ISendService/GetMessagesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MessageInfo[]> GetMessagesAsync(string userName, string password, int messageType, string[] fromNumbers, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetInboxCount", ReplyAction="http://tempuri.org/ISendService/GetInboxCountResponse")]
        System.Threading.Tasks.Task<int> GetInboxCountAsync(string userName, string password, bool isRead);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendBatchSms", ReplyAction="http://tempuri.org/ISendService/SendBatchSmsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SendBatchSmsResponse> SendBatchSmsAsync(ServiceReference1.SendBatchSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetBatchDelivery", ReplyAction="http://tempuri.org/ISendService/GetBatchDeliveryResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBatchDeliveryResponse> GetBatchDeliveryAsync(ServiceReference1.GetBatchDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetSenderNumbers", ReplyAction="http://tempuri.org/ISendService/GetSenderNumbersResponse")]
        System.Threading.Tasks.Task<string> GetSenderNumbersAsync(string userName, string password);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SendSmsManyToMany", ReplyAction="http://tempuri.org/ISendService/SendSmsManyToManyResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SendSmsManyToManyResponse> SendSmsManyToManyAsync(ServiceReference1.SendSmsManyToManyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/GetDeliveryLikeToLike", ReplyAction="http://tempuri.org/ISendService/GetDeliveryLikeToLikeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetDeliveryLikeToLikeResponse> GetDeliveryLikeToLikeAsync(ServiceReference1.GetDeliveryLikeToLikeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/ExtractTelecomBlacklistNumbers", ReplyAction="http://tempuri.org/ISendService/ExtractTelecomBlacklistNumbersResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ExtractTelecomBlacklistNumbersResponse> ExtractTelecomBlacklistNumbersAsync(ServiceReference1.ExtractTelecomBlacklistNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/NumberIsInTelecomBlacklist", ReplyAction="http://tempuri.org/ISendService/NumberIsInTelecomBlacklistResponse")]
        System.Threading.Tasks.Task<int> NumberIsInTelecomBlacklistAsync(string userName, string password, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/CheckSmsContent", ReplyAction="http://tempuri.org/ISendService/CheckSmsContentResponse")]
        System.Threading.Tasks.Task<int> CheckSmsContentAsync(string userName, string password, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/Dummy", ReplyAction="http://tempuri.org/ISendService/DummyResponse")]
        System.Threading.Tasks.Task<int> DummyAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendService/SetReadMessage", ReplyAction="http://tempuri.org/ISendService/SetReadMessageResponse")]
        System.Threading.Tasks.Task<int> SetReadMessageAsync(string userName, string password, int[] messageIds);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fromNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isFlash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public byte[] status;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(string userName, string password, string fromNumber, string[] toNumbers, string messageContent, bool isFlash, long[] recId, byte[] status)
        {
            this.userName = userName;
            this.password = password;
            this.fromNumber = fromNumber;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.isFlash = isFlash;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] status;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(int SendSMSResult, long[] recId, byte[] status)
        {
            this.SendSMSResult = SendSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OTPSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OTPSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public long recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        public OTPSMSRequest()
        {
        }
        
        public OTPSMSRequest(string userName, string password, string toNumbers, string messageContent, long recId, byte status)
        {
            this.userName = userName;
            this.password = password;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OTPSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OTPSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int OTPSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte status;
        
        public OTPSMSResponse()
        {
        }
        
        public OTPSMSResponse(int OTPSMSResult, long recId, byte status)
        {
            this.OTPSMSResult = OTPSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmartOTPSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmartOTPSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public long recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        public SmartOTPSMSRequest()
        {
        }
        
        public SmartOTPSMSRequest(string userName, string password, string toNumbers, string messageContent, long recId, byte status)
        {
            this.userName = userName;
            this.password = password;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmartOTPSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SmartOTPSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SmartOTPSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte status;
        
        public SmartOTPSMSResponse()
        {
        }
        
        public SmartOTPSMSResponse(int SmartOTPSMSResult, long recId, byte status)
        {
            this.SmartOTPSMSResult = SmartOTPSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBatchSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendBatchSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fromNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] toNumbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string messageContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isFlash;
        
        public SendBatchSmsRequest()
        {
        }
        
        public SendBatchSmsRequest(string userName, string password, string fromNumber, string[] toNumbers, string messageContent, bool isFlash)
        {
            this.userName = userName;
            this.password = password;
            this.fromNumber = fromNumber;
            this.toNumbers = toNumbers;
            this.messageContent = messageContent;
            this.isFlash = isFlash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBatchSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendBatchSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendBatchSmsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int batchSmsId;
        
        public SendBatchSmsResponse()
        {
        }
        
        public SendBatchSmsResponse(int SendBatchSmsResult, int batchSmsId)
        {
            this.SendBatchSmsResult = SendBatchSmsResult;
            this.batchSmsId = batchSmsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBatchDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int batchSmsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int count;
        
        public GetBatchDeliveryRequest()
        {
        }
        
        public GetBatchDeliveryRequest(string userName, string password, int batchSmsId, int index, int count)
        {
            this.userName = userName;
            this.password = password;
            this.batchSmsId = batchSmsId;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBatchDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetBatchDeliveryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] numbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] deliveryStatus;
        
        public GetBatchDeliveryResponse()
        {
        }
        
        public GetBatchDeliveryResponse(int GetBatchDeliveryResult, string[] numbers, int[] deliveryStatus)
        {
            this.GetBatchDeliveryResult = GetBatchDeliveryResult;
            this.numbers = numbers;
            this.deliveryStatus = deliveryStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsManyToMany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsManyToManyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string From;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public ServiceReference1.CorrespondingSendViaHttpPostDetailsModel[] model;
        
        public SendSmsManyToManyRequest()
        {
        }
        
        public SendSmsManyToManyRequest(string UserName, string Password, string From, ServiceReference1.CorrespondingSendViaHttpPostDetailsModel[] model)
        {
            this.UserName = UserName;
            this.Password = Password;
            this.From = From;
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsManyToManyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsManyToManyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSmsManyToManyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int smsId;
        
        public SendSmsManyToManyResponse()
        {
        }
        
        public SendSmsManyToManyResponse(int SendSmsManyToManyResult, int smsId)
        {
            this.SendSmsManyToManyResult = SendSmsManyToManyResult;
            this.smsId = smsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryLikeToLike", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryLikeToLikeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int smsId;
        
        public GetDeliveryLikeToLikeRequest()
        {
        }
        
        public GetDeliveryLikeToLikeRequest(string userName, string password, int smsId)
        {
            this.userName = userName;
            this.password = password;
            this.smsId = smsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryLikeToLikeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryLikeToLikeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetDeliveryLikeToLikeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] numbers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] deliveryStatus;
        
        public GetDeliveryLikeToLikeResponse()
        {
        }
        
        public GetDeliveryLikeToLikeResponse(int GetDeliveryLikeToLikeResult, string[] numbers, int[] deliveryStatus)
        {
            this.GetDeliveryLikeToLikeResult = GetDeliveryLikeToLikeResult;
            this.numbers = numbers;
            this.deliveryStatus = deliveryStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTelecomBlacklistNumbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExtractTelecomBlacklistNumbersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string numbers;
        
        public ExtractTelecomBlacklistNumbersRequest()
        {
        }
        
        public ExtractTelecomBlacklistNumbersRequest(string userName, string password, string numbers)
        {
            this.userName = userName;
            this.password = password;
            this.numbers = numbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTelecomBlacklistNumbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExtractTelecomBlacklistNumbersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ExtractTelecomBlacklistNumbersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] blacklistNumbers;
        
        public ExtractTelecomBlacklistNumbersResponse()
        {
        }
        
        public ExtractTelecomBlacklistNumbersResponse(int ExtractTelecomBlacklistNumbersResult, string[] blacklistNumbers)
        {
            this.ExtractTelecomBlacklistNumbersResult = ExtractTelecomBlacklistNumbersResult;
            this.blacklistNumbers = blacklistNumbers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISendServiceChannel : ServiceReference1.ISendService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SendServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ISendService>, ServiceReference1.ISendService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendServiceClient() : 
                base(SendServiceClient.GetDefaultBinding(), SendServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISendService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), SendServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendSMSResponse> SendSMSAsync(ServiceReference1.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.OTPSMSResponse> OTPSMSAsync(ServiceReference1.OTPSMSRequest request)
        {
            return base.Channel.OTPSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SmartOTPSMSResponse> SmartOTPSMSAsync(ServiceReference1.SmartOTPSMSRequest request)
        {
            return base.Channel.SmartOTPSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password)
        {
            return base.Channel.GetCreditAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<long> GetDeilveryAsync(string userName, string password, long recId)
        {
            return base.Channel.GetDeilveryAsync(userName, password, recId);
        }
        
        public System.Threading.Tasks.Task<long> GetDeliveryAsync(string userName, string password, long recId)
        {
            return base.Channel.GetDeliveryAsync(userName, password, recId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MessageInfo[]> GetMessagesAsync(string userName, string password, int messageType, string[] fromNumbers, int index, int count)
        {
            return base.Channel.GetMessagesAsync(userName, password, messageType, fromNumbers, index, count);
        }
        
        public System.Threading.Tasks.Task<int> GetInboxCountAsync(string userName, string password, bool isRead)
        {
            return base.Channel.GetInboxCountAsync(userName, password, isRead);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendBatchSmsResponse> SendBatchSmsAsync(ServiceReference1.SendBatchSmsRequest request)
        {
            return base.Channel.SendBatchSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBatchDeliveryResponse> GetBatchDeliveryAsync(ServiceReference1.GetBatchDeliveryRequest request)
        {
            return base.Channel.GetBatchDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> GetSenderNumbersAsync(string userName, string password)
        {
            return base.Channel.GetSenderNumbersAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendSmsManyToManyResponse> SendSmsManyToManyAsync(ServiceReference1.SendSmsManyToManyRequest request)
        {
            return base.Channel.SendSmsManyToManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetDeliveryLikeToLikeResponse> GetDeliveryLikeToLikeAsync(ServiceReference1.GetDeliveryLikeToLikeRequest request)
        {
            return base.Channel.GetDeliveryLikeToLikeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ExtractTelecomBlacklistNumbersResponse> ExtractTelecomBlacklistNumbersAsync(ServiceReference1.ExtractTelecomBlacklistNumbersRequest request)
        {
            return base.Channel.ExtractTelecomBlacklistNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> NumberIsInTelecomBlacklistAsync(string userName, string password, string number)
        {
            return base.Channel.NumberIsInTelecomBlacklistAsync(userName, password, number);
        }
        
        public System.Threading.Tasks.Task<int> CheckSmsContentAsync(string userName, string password, string message)
        {
            return base.Channel.CheckSmsContentAsync(userName, password, message);
        }
        
        public System.Threading.Tasks.Task<int> DummyAsync(int number)
        {
            return base.Channel.DummyAsync(number);
        }
        
        public System.Threading.Tasks.Task<int> SetReadMessageAsync(string userName, string password, int[] messageIds)
        {
            return base.Channel.SetReadMessageAsync(userName, password, messageIds);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISendService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISendService))
            {
                return new System.ServiceModel.EndpointAddress("http://payamakapi.ir/SendService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SendServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISendService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SendServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISendService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISendService,
        }
    }
}
